name: Modrinth Publishing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Execute perm for Gradle
        run: chmod +x gradlew
      - name: Publish the things!
        run: ./gradlew build publishModrinth --stacktrace
        env:
          MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
